name: Auto approve

on:
  pull_request_target:
    types: [opened, reopened]


jobs:
  run_if:
    if: startsWith(github.event.pull_request.head_ref, 'hotfix/')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: hmarr/auto-approve-action@v3