name: Auto approve

on:
  pull_request_target:
    types: [opened, reopened]


jobs:
  auto_approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: startsWith(github.event.pull_request.head_ref, 'hotfix/')
    steps:
      - uses: hmarr/auto-approve-action@v3
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
